title: Parity Public License
description: the free for open source license
url: https://paritylicense.com
homepage: https://paritylicense.com
image: https://paritylicense.com/logo-on-white.png
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
collections:
  versions:
    output: true
  diffs:
    output: true
  projects:
    output: true
